---
- name: How to output to the screen with debug 
  hosts: localhost 
  gather_facts: no



  vars: 
    vendorip: '192.168.22.55'


  tasks: 
  - name: Print out to the screen 
    debug: 
      msg: "Welcome to Ansible" 

  - name: Print a message variable 
    debug: 
      msg: "The vendor IP is: {{ vendorip }}"


  - name: Print just a variable 
    debug: 
      var: vendorip
      verbosity: 2 
