#!/usr/bin/env python3

farms = [{"name": "NE Farm", "agriculture": ["sheep", "cows", "pigs", "chickens", "llamas", "cats"]},
         {"name": "W Farm", "agriculture": ["pigs", "chickens", "llamas"]},
         {"name": "SE Farm", "agriculture": ["chickens", "carrots", "celery"]}]



for i in farms[0]:
    print(farms[0][i])

for i in farms[1]:
    print(farms[1][i])

for i in farms[2]:
    print(farms[2][i]) 


